// <auto-generated />
using System;
using FilesBrowser.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilesBrowser.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240312085444_01Initialization")]
    partial class _01Initialization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("FilesBrowser.Models.Folder", b =>
                {
                    b.Property<Guid>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("TEXT");

                    b.HasKey("FolderId");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("Folders");

                    b.HasData(
                        new
                        {
                            FolderId = new Guid("6a9c035c-bfb1-43e7-a7de-d2c09dafcbfa"),
                            Name = "Root"
                        },
                        new
                        {
                            FolderId = new Guid("1b94899c-9b2f-4026-bcce-79f627faeb9b"),
                            Name = "Music",
                            ParentFolderId = new Guid("6a9c035c-bfb1-43e7-a7de-d2c09dafcbfa")
                        },
                        new
                        {
                            FolderId = new Guid("91e45580-1b20-4ea4-a62d-fbd48b93d373"),
                            Name = "Images",
                            ParentFolderId = new Guid("6a9c035c-bfb1-43e7-a7de-d2c09dafcbfa")
                        },
                        new
                        {
                            FolderId = new Guid("cd55ec91-72a6-4e3b-927c-30cc0b4cb38b"),
                            Name = "Orchestral",
                            ParentFolderId = new Guid("1b94899c-9b2f-4026-bcce-79f627faeb9b")
                        },
                        new
                        {
                            FolderId = new Guid("a888d7d1-14e1-405d-b914-13c3246f082c"),
                            Name = "Pop",
                            ParentFolderId = new Guid("1b94899c-9b2f-4026-bcce-79f627faeb9b")
                        },
                        new
                        {
                            FolderId = new Guid("f43248cd-ed46-4ca1-a2e6-2a79ed4062e1"),
                            Name = "Rock",
                            ParentFolderId = new Guid("1b94899c-9b2f-4026-bcce-79f627faeb9b")
                        },
                        new
                        {
                            FolderId = new Guid("94820b8f-9f4f-4ed8-bfeb-a60f099404bf"),
                            Name = "Family",
                            ParentFolderId = new Guid("91e45580-1b20-4ea4-a62d-fbd48b93d373")
                        },
                        new
                        {
                            FolderId = new Guid("7ce23ddf-607d-4d91-8fa8-58ea5edd0602"),
                            Name = "Wallpapers",
                            ParentFolderId = new Guid("91e45580-1b20-4ea4-a62d-fbd48b93d373")
                        },
                        new
                        {
                            FolderId = new Guid("a104755d-a02c-4b91-a1b9-37c8180fb82d"),
                            Name = "Screenshots",
                            ParentFolderId = new Guid("91e45580-1b20-4ea4-a62d-fbd48b93d373")
                        });
                });

            modelBuilder.Entity("FilesBrowser.Models.Folder", b =>
                {
                    b.HasOne("FilesBrowser.Models.Folder", "ParentFolder")
                        .WithMany("Folders")
                        .HasForeignKey("ParentFolderId");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("FilesBrowser.Models.Folder", b =>
                {
                    b.Navigation("Folders");
                });
#pragma warning restore 612, 618
        }
    }
}
